import type { Metadata } from "next";
import {Noto_Kufi_Arabic} from "next/font/google"
import "./globals.css";
import { ThemeProvider } from "@/components/theme/theme-provider"

const font = Noto_Kufi_Arabic({ subsets: ["arabic"]})

export const metadata: Metadata = {
  // title: "Create Next App",
  // description: "Generated by create next app",
  icons: "/logo-icon.png",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" className="scroll-smooth">
      <body
        className={font.className}
      >
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
      </body>
    </html>
  );
}
